{
 "title": "MQ Appliance - Exporters",
 "description": "Metrics about the MQ Appliance exporters",
 "tags": [ "MQA_Exporters" ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "appliance", "label": "Appliance", "query": { "query": "mqa_info" } }
  ]
 },
 "panels": [
  { "title": "Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Exporter Date/Time",
   "type": "stat",
   "description": "The current local date and time on the server running the Prometheus exporter.",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "mqa_exporter_info{appliance=\"$appliance\"}"
    }
   ]
  },
  {
   "title": "Appliance Date/Time",
   "type": "stat",
   "description": "The current local date and time on the appliance.",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "mqa_info{appliance=\"$appliance\"}"
    }
   ]
  },
  { "title": "Local Date and Time", "type": "grafana-clock-panel", "gridPos": { "h": 6, "w": 3, "x": 8, "y": 1 } },
  {
   "title": "Exporter Timezone",
   "type": "stat",
   "description": "The name of the time zone currently in effect on the server running the Prometheus exporter.",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "mqa_exporter_info{appliance=\"$appliance\"}"
    }
   ]
  },
  {
   "title": "Appliance Timezone",
   "type": "stat",
   "description": "The name of the time zone currently in effect.",
   "gridPos": { "h": 2, "w": 3, "x": 5, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "mqa_info{appliance=\"$appliance\"}"
    }
   ]
  },
  {
   "title": "Exporter Version",
   "type": "stat",
   "description": "The exporter version number of the Prometheus exporter.",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "mqa_exporter_info{appliance=\"$appliance\"}"
    }
   ]
  },
  {
   "title": "Appliance Version",
   "type": "stat",
   "description": "The version of this firmware image.",
   "gridPos": { "h": 2, "w": 3, "x": 5, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "mqa_info{appliance=\"$appliance\"}"
    }
   ]
  },
  { "title": "Collectors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Collectors - Elapsed Time",
   "type": "graph",
   "description": "Elapsed time for the  collectors",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "mqa_exporter_active_users_elapsed_time_seconds{appliance=\"$appliance\"}",
     "legendFormat": "Active Users"
    },
    {
     "expr": "mqa_exporter_current_sensors_elapsed_time_seconds{appliance=\"$appliance\"}",
     "legendFormat": "Current Sensors"
    },
    {
     "expr": "mqa_exporter_environmental_fan_sensors_elapsed_time_seconds{appliance=\"$appliance\"}",
     "legendFormat": "Env. Fan Sensors"
    },
    {
     "expr": "mqa_exporter_environmental_sensors_elapsed_time_seconds{appliance=\"$appliance\"}",
     "legendFormat": "Env. Sensors"
    },
    {
     "expr": "mqa_exporter_ethernet_counters_elapsed_time_seconds{appliance=\"$appliance\"}",
     "legendFormat": "Ethernet Counters"
    },
    {
     "expr": "mqa_exporter_failure_notification_elapsed_time_seconds{appliance=\"$appliance\"}",
     "legendFormat": "Failure Notification"
    },
    {
     "expr": "mqa_exporter_file_system_elapsed_time_seconds{appliance=\"$appliance\"}",
     "legendFormat": "File  System"
    },
    {
     "expr": "mqa_exporter_ipmi_sel_events_elapsed_time_seconds{appliance=\"$appliance\"}",
     "legendFormat": "IPMI SEL Events"
    },
    {
     "expr": "mqa_exporter_log_targets_elapsed_time_seconds{appliance=\"$appliance\"}",
     "legendFormat": "Log Targets"
    },
    {
     "expr": "mqa_exporter_mq_system_resources_elapsed_time_seconds{appliance=\"$appliance\"}",
     "legendFormat": "MQ System Resources"
    },
    {
     "expr": "mqa_exporter_mqa_information_elapsed_time_seconds{appliance=\"$appliance\"}",
     "legendFormat": "MQA Information"
    },
    {
     "expr": "mqa_exporter_network_interfaces_elapsed_time_seconds{appliance=\"$appliance\"}",
     "legendFormat": "Network Interfaces"
    },
    {
     "expr": "mqa_exporter_other_sensors_elapsed_time_seconds{appliance=\"$appliance\"}",
     "legendFormat": "Other Sensors"
    },
    {
     "expr": "mqa_exporter_queue_managers_elapsed_time_seconds{appliance=\"$appliance\"}",
     "legendFormat": "Queue Managers"
    },
    {
     "expr": "mqa_exporter_raid_ssd_elapsed_time_seconds{appliance=\"$appliance\"}",
     "legendFormat": "Raid SSD"
    },
    {
     "expr": "mqa_exporter_system_cpu_elapsed_time_seconds{appliance=\"$appliance\"}",
     "legendFormat": "System CPU"
    },
    {
     "expr": "mqa_exporter_system_memory_elapsed_time_seconds{appliance=\"$appliance\"}",
     "legendFormat": "System Memory"
    },
    {
     "expr": "mqa_exporter_tcp_summary_elapsed_time_seconds{appliance=\"$appliance\"}",
     "legendFormat": "TCP Summary"
    },
    {
     "expr": "mqa_exporter_temperature_sensors_elapsed_time_seconds{appliance=\"$appliance\"}",
     "legendFormat": "Temperature Sensors"
    },
    {
     "expr": "mqa_exporter_voltage_sensors_elapsed_time_seconds{appliance=\"$appliance\"}",
     "legendFormat": "Voltage Sensors"
    }
   ]
  }
 ]
}