{
 "title": "MQ Appliance - Main",
 "description": "Metrics about the MQ Appliance hardware",
 "tags": [ "MQA_Main" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "appliance", "label": "Appliance", "query": { "query": "mqa_info" } }
  ]
 },
 "panels": [
  { "title": "Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Date/Time",
   "type": "stat",
   "description": "The current local date and time on the appliance.",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "time:ddd MMM DD HH:mm:ss YYYY" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "mqa_current_datetime_seconds_total{appliance=\"$appliance\"} * 1000"
    }
   ]
  },
  {
   "title": "Timezone",
   "type": "stat",
   "description": "The name of the time zone currently in effect.",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "mqa_info{appliance=\"$appliance\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "The total amount of time the appliance has been up since the last reload or reboot. Note that a shutdown and reload resets this counter.",
   "gridPos": { "h": 2, "w": 4, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "mqa_uptime_seconds_total{appliance=\"$appliance\"}"
    }
   ]
  },
  {
   "title": "Boot Up Time",
   "type": "stat",
   "description": "The total amount of time since the last reboot. Note that this counter is reset by a shutdown and reboot, but not by a shutdown and reload.",
   "gridPos": { "h": 2, "w": 4, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "mqa_bootuptime_seconds_total{appliance=\"$appliance\"}"
    }
   ]
  },
  {
   "title": "Type",
   "type": "stat",
   "description": "The type of the firmware installation type. Can be primary or secondary. The secondary firmware image is used when rolling back the firmware.",
   "gridPos": { "h": 2, "w": 2, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "mqa_info{appliance=\"$appliance\"}"
    }
   ]
  },
  { "title": "Local Date and Time", "type": "grafana-clock-panel", "gridPos": { "h": 4, "w": 3, "x": 16, "y": 1 } },
  {
   "title": "Exporter Date/Time",
   "type": "stat",
   "description": "The current local date and time on the server running the Prometheus exporter.",
   "gridPos": { "h": 2, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "time:ddd MMM DD HH:mm:ss YYYY" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(mqa_exporter_current_datetime_seconds_total{appliance=\"$appliance\"} * 1000)"
    }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "description": "The version of this firmware image.",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "mqa_info{appliance=\"$appliance\"}"
    }
   ]
  },
  {
   "title": "Level",
   "type": "stat",
   "description": "The level of the firmware.",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "mqa_info{appliance=\"$appliance\"}"
    }
   ]
  },
  {
   "title": "Delivery Type",
   "type": "stat",
   "description": "Delivery type of the firmware.",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "mqa_info{appliance=\"$appliance\"}"
    }
   ]
  },
  {
   "title": "Build",
   "type": "stat",
   "description": "The specific build of the firmware image.",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "mqa_info{appliance=\"$appliance\"}"
    }
   ]
  },
  {
   "title": "Build Date",
   "type": "stat",
   "description": "Date of the firmware build.",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "mqa_info{appliance=\"$appliance\"}"
    }
   ]
  },
  {
   "title": "Install Date",
   "type": "stat",
   "description": "Date that the firmware was installed.",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "mqa_info{appliance=\"$appliance\"}"
    }
   ]
  },
  {
   "title": "Boot Count",
   "type": "stat",
   "description": "The number of times the firmware image was restarted through an appliance reboot or a firmware reload. The count is from the initial firmware load on the appliance till the current time. The count is independent of firmware version.",
   "gridPos": { "h": 2, "w": 2, "x": 14, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "mqa_bootcount_total{appliance=\"$appliance\"}"
    }
   ]
  },
  {
   "title": "Exporter Timezone",
   "type": "stat",
   "description": "The name of the time zone currently in effect on the server running the Prometheus exporter.",
   "gridPos": { "h": 2, "w": 3, "x": 19, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(mqa_exporter_info{appliance=\"$appliance\"}) by (localTimezone)"
    }
   ]
  },
  {
   "title": "Exporter Version",
   "type": "stat",
   "description": "The exporter version number of the Prometheus exporter.",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(mqa_exporter_info{appliance=\"$appliance\"}) by (version)"
    }
   ]
  },
  {
   "title": "Serial #",
   "type": "stat",
   "description": "The serial number of the appliance. This number is unique to each appliance.",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "mqa_info{appliance=\"$appliance\"}"
    }
   ]
  },
  {
   "title": "Machine Type",
   "type": "stat",
   "description": "The IBM machine type of the appliance.",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "mqa_info{appliance=\"$appliance\"}"
    }
   ]
  },
  {
   "title": "Model Type",
   "type": "stat",
   "description": "The IBM model type of the appliance.",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "mqa_info{appliance=\"$appliance\"}"
    }
   ]
  },
  {
   "title": "Intrusion Detected",
   "type": "stat",
   "description": "Whether intrusion has been detected in the appliance.",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mqa_other_sensor_intrusion_detected{appliance=\"$appliance\"}"
    }
   ]
  },
  {
   "title": "HA Status",
   "type": "stat",
   "description": "HA status of the appliance if the appliance is part of an HA group",
   "gridPos": { "h": 2, "w": 2, "x": 9, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mqa_mq_resources_ha_status{appliance=\"$appliance\"}"
    }
   ]
  },
  {
   "title": "HA Partner",
   "type": "stat",
   "description": "Appliance name of the HA partner and its associated status",
   "gridPos": { "h": 2, "w": 4, "x": 11, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "mqa_mq_resources_info{appliance=\"$appliance\"}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": " CPU Usage",
     "type": "gauge",
     "description": "Current total CPU usage on the appliance",
     "gridPos": { "h": 5, "w": 2, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "mqa_system_cpu_usage{appliance=\"$appliance\"}"
      }
     ]
    },
    {
     "title": "CPU Load Avg",
     "type": "graph",
     "description": "CPU load average for 1, 5 and 15 minutes",
     "gridPos": { "h": 5, "w": 10, "x": 2, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "mqa_system_cpu_load_avg_1m{appliance=\"$appliance\"}",
       "legendFormat": "CPU Load Avg 1m"
      },
      {
       "expr": "mqa_system_cpu_load_avg_5m{appliance=\"$appliance\"}",
       "legendFormat": "CPU Load Avg 5m"
      },
      {
       "expr": "mqa_system_cpu_load_avg_15m{appliance=\"$appliance\"}",
       "legendFormat": "CPU Load Avg 15m"
      }
     ]
    },
    {
     "title": "CPU Temperatures",
     "type": "bargauge",
     "description": "CPU temperatures over time",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 36 }
     ]
    },
    {
     "title": "CPU Temperatures",
     "type": "graph",
     "description": "CPU temperatures over time",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "yaxes": [
      { "format": "celsius" }
     ],
     "targets": [
      {
       "expr": "mqa_environmental_sensors_cpu_1_temperature_celsius{appliance=\"$appliance\"}",
       "legendFormat": "CPU 1"
      },
      {
       "expr": "mqa_environmental_sensors_cpu_2_temperature_celsius{appliance=\"$appliance\"}",
       "legendFormat": "CPU 2"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "graph",
     "description": "CPU usage overtime.",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "mqa_system_cpu_usage{appliance=\"$appliance\"}",
       "legendFormat": "CPU"
      },
      {
       "expr": "sum(mqa_queue_manager_cpu_usage{appliance=\"$appliance\"})",
       "legendFormat": "Queue Managers"
      }
     ]
    }
   ]
  },
  {
   "title": "Failure Notifications",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Failures",
     "type": "stat",
     "description": "Total number of existing failure notifications.",
     "gridPos": { "h": 5, "w": 2, "x": 0, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "count(mqa_failure_notification_info{appliance=\"$appliance\"})"
      }
     ]
    },
    {
     "title": "Failure Notifications",
     "type": "table",
     "description": "Failures that have been notified.",
     "gridPos": { "h": 5, "w": 13, "x": 2, "y": 9 },
     "targets": [
      {
       "expr": "mqa_failure_notification_info{appliance=\"$appliance\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Fans",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Fan 1 RPM",
     "type": "stat",
     "description": "RPM for fan 1",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "rotrpm" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "mqa_environmental_fan_sensors_fan_speed_rpm{appliance=\"$appliance\", fanID=\"fan-1\"}",
       "legendFormat": "{{readingStatus}}"
      }
     ]
    },
    {
     "title": "Fan 2 RPM",
     "type": "stat",
     "description": "RPM for fan 2",
     "gridPos": { "h": 3, "w": 4, "x": 4, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "rotrpm" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "mqa_environmental_fan_sensors_fan_speed_rpm{appliance=\"$appliance\", fanID=\"fan-2\"}",
       "legendFormat": "{{readingStatus}}"
      }
     ]
    },
    {
     "title": "Fan 3 RPM",
     "type": "stat",
     "description": "RPM for fan 3",
     "gridPos": { "h": 3, "w": 4, "x": 8, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "rotrpm" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "mqa_environmental_fan_sensors_fan_speed_rpm{appliance=\"$appliance\", fanID=\"fan-3\"}",
       "legendFormat": "{{readingStatus}}"
      }
     ]
    }
   ]
  },
  {
   "title": "IPMI Events",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "IPMI SEL Events",
     "type": "table",
     "description": "Intelligent Platform Management Interface (IPMI) System Event Log (SEL) events that the Baseboard Management Controller (BMC) collected.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "mqa_ipmi_sel_events_info{appliance=\"$appliance\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Log Targets",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Log Targets",
     "type": "table",
     "description": "The list of log targets currently defined and in use on this appliance",
     "gridPos": { "h": 6, "w": 14, "x": 0, "y": 12 },
     "targets": [
      {
       "expr": "mqa_log_target_info{appliance=\"$appliance\"}"
      }
     ]
    },
    {
     "title": "Total Events Processed",
     "type": "stat",
     "description": "The total number of events processed for all  log targets",
     "gridPos": { "h": 2, "w": 4, "x": 17, "y": 12 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(mqa_log_target_events_processed_total{appliance=\"$appliance\"})",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Total Events Pending",
     "type": "stat",
     "description": "The total number of events pending for all  log targets",
     "gridPos": { "h": 2, "w": 4, "x": 17, "y": 14 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(mqa_log_target_events_pending_total{appliance=\"$appliance\"})",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Total Events Dropped",
     "type": "stat",
     "description": "The total number of events dropped for all  log targets",
     "gridPos": { "h": 2, "w": 4, "x": 17, "y": 16 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(mqa_log_target_events_dropped_total{appliance=\"$appliance\"})",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Events Processed",
     "type": "stat",
     "description": "The total number of events processed by log targets",
     "gridPos": { "h": 4, "w": 14, "x": 0, "y": 18 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "mqa_log_target_events_processed_total{appliance=\"$appliance\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Events Processed Rate",
     "type": "graph",
     "description": "The rate of log targets events processed",
     "gridPos": { "h": 4, "w": 10, "x": 14, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(mqa_log_target_events_processed_total{appliance=\"$appliance\"}[2m])",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Events Pending",
     "type": "stat",
     "description": "The total number of events pending by log targets",
     "gridPos": { "h": 4, "w": 14, "x": 0, "y": 22 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "mqa_log_target_events_pending_total{appliance=\"$appliance\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Events Pending  Rate",
     "type": "graph",
     "description": "The rate of log targets events pending",
     "gridPos": { "h": 4, "w": 10, "x": 14, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(mqa_log_target_events_pending_total{appliance=\"$appliance\"}[2m])",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Events Dropped",
     "type": "stat",
     "description": "The total number of events dropped by log targets",
     "gridPos": { "h": 4, "w": 14, "x": 0, "y": 26 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "mqa_log_target_events_dropped_total{appliance=\"$appliance\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Events Dropped  Rate",
     "type": "graph",
     "description": "The rate of log targets events dropped",
     "gridPos": { "h": 4, "w": 10, "x": 14, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(mqa_log_target_events_dropped_total{appliance=\"$appliance\"}[2m])",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory",
     "type": "gauge",
     "description": "Memory percentage currently in use",
     "gridPos": { "h": 5, "w": 2, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "mqa_system_memory_memory_usage{appliance=\"$appliance\"}"
      }
     ]
    },
    {
     "title": "Total Memory",
     "type": "stat",
     "description": "Total memory available on the appliance",
     "gridPos": { "h": 5, "w": 5, "x": 2, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "mqa_system_memory_memory_bytes_total{appliance=\"$appliance\"}"
      }
     ]
    },
    {
     "title": "Used Memory",
     "type": "stat",
     "description": "Amount of memory currently being used on the appliance",
     "gridPos": { "h": 5, "w": 5, "x": 7, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "mqa_system_memory_memory_bytes_used{appliance=\"$appliance\"}"
      }
     ]
    },
    {
     "title": "Free Memory",
     "type": "stat",
     "description": "Amount of memory currently available on the appliance",
     "gridPos": { "h": 5, "w": 5, "x": 12, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "mqa_system_memory_memory_bytes_free{appliance=\"$appliance\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Networking",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network Interfaces Status",
     "type": "table",
     "description": "Status of all network interfaces.",
     "gridPos": { "h": 6, "w": 17, "x": 0, "y": 14 },
     "targets": [
      {
       "expr": "sort(mqa_network_interface_info{appliance=\"$appliance\"})"
      }
     ]
    },
    {
     "title": "RX Bytes Rate",
     "type": "graph",
     "description": "Receive rate for all interfaces",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "rate(mqa_network_interface_rx_bytes_total{appliance=\"$appliance\"}[5m])",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "TX Bytes Rate",
     "type": "graph",
     "description": "Transmit rate for all interfaces",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "rate(mqa_network_interface_tx_bytes_total{appliance=\"$appliance\"}[5m])",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "TCP Established",
     "type": "graph",
     "description": "Number of TCP connections established",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "mqa_tcp_connections_established{appliance=\"$appliance\"}",
       "legendFormat": "Connections"
      }
     ]
    },
    {
     "title": "TCP Listening",
     "type": "graph",
     "description": "Number of TCP listeners currently active",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "mqa_tcp_connections_listen{appliance=\"$appliance\"}",
       "legendFormat": "Listeners"
      }
     ]
    }
   ]
  },
  {
   "title": "Power Supplies",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "PS 1 - Present",
     "type": "stat",
     "description": "Whether Power Supply #1 is present in the appliance.",
     "gridPos": { "h": 2, "w": 2, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "mqa_other_sensor_power_supply_1_present{appliance=\"$appliance\"}"
      }
     ]
    },
    {
     "title": "PS 1 - Enabled",
     "type": "stat",
     "description": "Whether Power Supply #1 is enabled in the appliance.",
     "gridPos": { "h": 2, "w": 2, "x": 2, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "mqa_other_sensor_power_supply_1_not_enabled{appliance=\"$appliance\"}"
      }
     ]
    },
    {
     "title": "PS 1 - Lost AC",
     "type": "stat",
     "description": "Whether Power Supply #1 has lost AC in the appliance.",
     "gridPos": { "h": 2, "w": 2, "x": 4, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "mqa_other_sensor_power_supply_1_ac_lost{appliance=\"$appliance\"}"
      }
     ]
    },
    {
     "title": "PS 1 - Failure",
     "type": "stat",
     "description": "Whether Power Supply #1 has failed in the appliance.",
     "gridPos": { "h": 2, "w": 2, "x": 6, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "mqa_other_sensor_power_supply_1_output_failure{appliance=\"$appliance\"}"
      }
     ]
    },
    {
     "title": "PS 2 - Present",
     "type": "stat",
     "description": "Whether Power Supply #2 is present in the appliance.",
     "gridPos": { "h": 2, "w": 2, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "mqa_other_sensor_power_supply_2_present{appliance=\"$appliance\"}"
      }
     ]
    },
    {
     "title": "PS 2 - Enabled",
     "type": "stat",
     "description": "Whether Power Supply #2 is enabled in the appliance.",
     "gridPos": { "h": 2, "w": 2, "x": 2, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "mqa_other_sensor_power_supply_2_not_enabled{appliance=\"$appliance\"}"
      }
     ]
    },
    {
     "title": "PS 2 - Lost AC",
     "type": "stat",
     "description": "Whether Power Supply #2 has lost AC in the appliance.",
     "gridPos": { "h": 2, "w": 2, "x": 4, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "mqa_other_sensor_power_supply_2_ac_lost{appliance=\"$appliance\"}"
      }
     ]
    },
    {
     "title": "PS 2 - Failure",
     "type": "stat",
     "description": "Whether Power Supply #2 has failed in the appliance.",
     "gridPos": { "h": 2, "w": 2, "x": 6, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "mqa_other_sensor_power_supply_2_output_failure{appliance=\"$appliance\"}"
      }
     ]
    }
   ]
  },
  { "title": "Queue Managers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Total",
   "type": "stat",
   "description": "Total queue managers defined on this appliance",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(mqa_queue_manager_info{appliance=\"$appliance\"})"
    }
   ]
  },
  {
   "title": "Running",
   "type": "stat",
   "description": "Total queue managers in 'Running' state on this appliance",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(mqa_queue_manager_info{appliance=\"$appliance\", status=\"Running\"})",
     "legendFormat": "{{Status}}"
    }
   ]
  },
  {
   "title": "Running elsewhere",
   "type": "stat",
   "description": "Total queue managers in 'Running elsewhere' state on this appliance",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(mqa_queue_manager_info{appliance=\"$appliance\", status=\"Running elsewhere\"})",
     "legendFormat": "{{Status}}"
    }
   ]
  },
  {
   "title": "Ended",
   "type": "stat",
   "description": "Total queue managers in 'Ended' state on this appliance",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(mqa_queue_manager_info{appliance=\"$appliance\", status=~\"End.*\"})"
    }
   ]
  },
  {
   "title": "Starting",
   "type": "stat",
   "description": "Total queue managers in 'Starting' state on this appliance",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(mqa_queue_manager_info{appliance=\"$appliance\", status=~\"Starting\"})"
    }
   ]
  },
  {
   "title": "Quiescing",
   "type": "stat",
   "description": "Total queue managers in 'Quiescing' state on this appliance",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(mqa_queue_manager_info{appliance=\"$appliance\", status=~\"Quiescing\"})"
    }
   ]
  },
  {
   "title": "CPU Usage by running queue managers (highest to lowest)",
   "type": "gauge",
   "description": "CPU Usage by running queue managers (highest to lowest)",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(mqa_queue_manager_cpu_usage{appliance=\"$appliance\", status=\"Running\"})",
     "legendFormat": "{{qm}}"
    }
   ]
  },
  {
   "title": "Queue Managers List",
   "type": "table",
   "description": "List of queue managers currently using the appliance.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "mqa_queue_manager_info{appliance=\"$appliance\"}"
    }
   ]
  },
  {
   "title": "CPU Usage by Queue Manager",
   "type": "graph",
   "description": "CPU usage by queue manager",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "mqa_queue_manager_cpu_usage{appliance=\"$appliance\"}",
     "legendFormat": "{{qm}}"
    }
   ]
  },
  {
   "title": "Memory Usage by Queue Manager",
   "type": "graph",
   "description": "Memory usage by queue manager",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "mqa_queue_manager_memory_bytes_used{appliance=\"$appliance\"}",
     "legendFormat": "{{qm}}"
    }
   ]
  },
  {
   "title": "File System Usage by Queue Manager",
   "type": "graph",
   "description": "File system usage by queue manager",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "mqa_queue_manager_fs_bytes_used{appliance=\"$appliance\"}",
     "legendFormat": "{{qm}}"
    }
   ]
  },
  {
   "title": "Raid SSDs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "panels": [
    {
     "title": "SSD #1",
     "type": "stat",
     "description": "First SSD drive serial number",
     "gridPos": { "h": 2, "w": 2, "x": 0, "y": 17 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "mqa_raid_ssd_bytes_written_total{appliance=\"$appliance\", diskNumber=\"1\"}"
      }
     ]
    },
    {
     "title": "State",
     "type": "stat",
     "description": "State of the physical drive",
     "gridPos": { "h": 2, "w": 2, "x": 2, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "mqa_raid_physical_drive_info{appliance=\"$appliance\", position=\"B5S1\"}"
      }
     ]
    },
    {
     "title": "Failure",
     "type": "stat",
     "description": "Whether the physical drive has failed",
     "gridPos": { "h": 2, "w": 2, "x": 4, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "mqa_raid_physical_drive_failure{appliance=\"$appliance\", position=\"B5S1\"}"
      }
     ]
    },
    {
     "title": "Data Written",
     "type": "stat",
     "description": "Amount of data in bytes written to the SSD since manufacturing",
     "gridPos": { "h": 2, "w": 2, "x": 6, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "mqa_raid_ssd_bytes_written_total{appliance=\"$appliance\", diskNumber=\"1\"}"
      }
     ]
    },
    {
     "title": "Life Left",
     "type": "stat",
     "description": "Life left in percent for the SSD",
     "gridPos": { "h": 2, "w": 2, "x": 8, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "mqa_raid_ssd_life_left{appliance=\"$appliance\", diskNumber=\"1\"}"
      }
     ]
    },
    {
     "title": "Temperature",
     "type": "bargauge",
     "description": "Temperature in celsius of the physical drive",
     "gridPos": { "h": 2, "w": 4, "x": 10, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "mqa_raid_physical_drive_temperature_celsius{appliance=\"$appliance\", position=\"B5S1\"}"
      }
     ]
    },
    {
     "title": "Vendor ID",
     "type": "stat",
     "description": "Product ID the physical drive. Manufacturer serial number",
     "gridPos": { "h": 2, "w": 2, "x": 14, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "mqa_raid_physical_drive_info{appliance=\"$appliance\", position=\"B5S1\"}"
      }
     ]
    },
    {
     "title": "Product ID",
     "type": "stat",
     "description": "Product ID the physical drive. Manufacturer serial number",
     "gridPos": { "h": 2, "w": 2, "x": 16, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "mqa_raid_physical_drive_info{appliance=\"$appliance\", position=\"B5S1\"}"
      }
     ]
    },
    {
     "title": "Size",
     "type": "stat",
     "description": "Size of the physical drive in bytes",
     "gridPos": { "h": 2, "w": 2, "x": 18, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "mqa_raid_physical_drive_coerced_size_bytes_total{appliance=\"$appliance\", position=\"B5S1\"}"
      }
     ]
    },
    {
     "title": "SSD #2",
     "type": "stat",
     "description": "Second SSD drive serial number",
     "gridPos": { "h": 2, "w": 2, "x": 0, "y": 19 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "mqa_raid_ssd_bytes_written_total{appliance=\"$appliance\", diskNumber=\"2\"}"
      }
     ]
    },
    {
     "title": "State",
     "type": "stat",
     "description": "State of the physical drive",
     "gridPos": { "h": 2, "w": 2, "x": 2, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "mqa_raid_physical_drive_info{appliance=\"$appliance\", position=\"B5S2\"}"
      }
     ]
    },
    {
     "title": "Failure",
     "type": "stat",
     "description": "Whether the physical drive has failed",
     "gridPos": { "h": 2, "w": 2, "x": 4, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "mqa_raid_physical_drive_failure{appliance=\"$appliance\", position=\"B5S2\"}"
      }
     ]
    },
    {
     "title": "Data Written",
     "type": "stat",
     "description": "Amount of data in bytes written to the SSD since manufacturing",
     "gridPos": { "h": 2, "w": 2, "x": 6, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "mqa_raid_ssd_bytes_written_total{appliance=\"$appliance\", diskNumber=\"2\"}"
      }
     ]
    },
    {
     "title": "Life Left",
     "type": "stat",
     "description": "Life left in percent for the SSD",
     "gridPos": { "h": 2, "w": 2, "x": 8, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "mqa_raid_ssd_life_left{appliance=\"$appliance\", diskNumber=\"2\"}"
      }
     ]
    },
    {
     "title": "Temperature",
     "type": "bargauge",
     "description": "Temperature in celsius of the physical drive",
     "gridPos": { "h": 2, "w": 4, "x": 10, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "mqa_raid_physical_drive_temperature_celsius{appliance=\"$appliance\", position=\"B5S2\"}"
      }
     ]
    },
    {
     "title": "Vendor ID",
     "type": "stat",
     "description": "Product ID the physical drive. Manufacturer serial number",
     "gridPos": { "h": 2, "w": 2, "x": 14, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "mqa_raid_physical_drive_info{appliance=\"$appliance\", position=\"B5S2\"}"
      }
     ]
    },
    {
     "title": "Product ID",
     "type": "stat",
     "description": "Product ID the physical drive. Manufacturer serial number",
     "gridPos": { "h": 2, "w": 2, "x": 16, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "mqa_raid_physical_drive_info{appliance=\"$appliance\", position=\"B5S2\"}"
      }
     ]
    },
    {
     "title": "Size",
     "type": "stat",
     "description": "Size of the physical drive in bytes",
     "gridPos": { "h": 2, "w": 2, "x": 18, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "mqa_raid_physical_drive_coerced_size_bytes_total{appliance=\"$appliance\", position=\"B5S2\"}"
      }
     ]
    },
    {
     "title": "SSD #3",
     "type": "stat",
     "description": "Third SSD drive serial number",
     "gridPos": { "h": 2, "w": 2, "x": 0, "y": 21 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "mqa_raid_ssd_bytes_written_total{appliance=\"$appliance\", diskNumber=\"3\"}"
      }
     ]
    },
    {
     "title": "State",
     "type": "stat",
     "description": "State of the physical drive",
     "gridPos": { "h": 2, "w": 2, "x": 2, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "mqa_raid_physical_drive_info{appliance=\"$appliance\", position=\"B7S1\"}"
      }
     ]
    },
    {
     "title": "Failure",
     "type": "stat",
     "description": "Whether the physical drive has failed",
     "gridPos": { "h": 2, "w": 2, "x": 4, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "mqa_raid_physical_drive_failure{appliance=\"$appliance\", position=\"B7S1\"}"
      }
     ]
    },
    {
     "title": "Data Written",
     "type": "stat",
     "description": "Amount of data in bytes written to the SSD since manufacturing",
     "gridPos": { "h": 2, "w": 2, "x": 6, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "mqa_raid_ssd_bytes_written_total{appliance=\"$appliance\", diskNumber=\"3\"}"
      }
     ]
    },
    {
     "title": "Life Left",
     "type": "stat",
     "description": "Life left in percent for the SSD",
     "gridPos": { "h": 2, "w": 2, "x": 8, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "mqa_raid_ssd_life_left{appliance=\"$appliance\", diskNumber=\"3\"}"
      }
     ]
    },
    {
     "title": "Temperature",
     "type": "bargauge",
     "description": "Temperature in celsius of the physical drive",
     "gridPos": { "h": 2, "w": 4, "x": 10, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "mqa_raid_physical_drive_temperature_celsius{appliance=\"$appliance\", position=\"B7S1\"}"
      }
     ]
    },
    {
     "title": "Vendor ID",
     "type": "stat",
     "description": "Product ID the physical drive. Manufacturer serial number",
     "gridPos": { "h": 2, "w": 2, "x": 14, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "mqa_raid_physical_drive_info{appliance=\"$appliance\", position=\"B7S1\"}"
      }
     ]
    },
    {
     "title": "Product ID",
     "type": "stat",
     "description": "Product ID the physical drive. Manufacturer serial number",
     "gridPos": { "h": 2, "w": 2, "x": 16, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "mqa_raid_physical_drive_info{appliance=\"$appliance\", position=\"B7S1\"}"
      }
     ]
    },
    {
     "title": "Size",
     "type": "stat",
     "description": "Size of the physical drive in bytes",
     "gridPos": { "h": 2, "w": 2, "x": 18, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "mqa_raid_physical_drive_coerced_size_bytes_total{appliance=\"$appliance\", position=\"B7S1\"}"
      }
     ]
    },
    {
     "title": "SSD #4",
     "type": "stat",
     "description": "Fourth SSD drive serial number",
     "gridPos": { "h": 2, "w": 2, "x": 0, "y": 23 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "mqa_raid_ssd_bytes_written_total{appliance=\"$appliance\", diskNumber=\"4\"}"
      }
     ]
    },
    {
     "title": "State",
     "type": "stat",
     "description": "State of the physical drive",
     "gridPos": { "h": 2, "w": 2, "x": 2, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "mqa_raid_physical_drive_info{appliance=\"$appliance\", position=\"B7S2\"}"
      }
     ]
    },
    {
     "title": "Failure",
     "type": "stat",
     "description": "Whether the physical drive has failed",
     "gridPos": { "h": 2, "w": 2, "x": 4, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "mqa_raid_physical_drive_failure{appliance=\"$appliance\", position=\"B7S2\"}"
      }
     ]
    },
    {
     "title": "Data Written",
     "type": "stat",
     "description": "Amount of data in bytes written to the SSD since manufacturing",
     "gridPos": { "h": 2, "w": 2, "x": 6, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "mqa_raid_ssd_bytes_written_total{appliance=\"$appliance\", diskNumber=\"4\"}"
      }
     ]
    },
    {
     "title": "Life Left",
     "type": "stat",
     "description": "Life left in percent for the SSD",
     "gridPos": { "h": 2, "w": 2, "x": 8, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "mqa_raid_ssd_life_left{appliance=\"$appliance\", diskNumber=\"4\"}"
      }
     ]
    },
    {
     "title": "Temperature",
     "type": "bargauge",
     "description": "Temperature in celsius of the physical drive",
     "gridPos": { "h": 2, "w": 4, "x": 10, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "mqa_raid_physical_drive_temperature_celsius{appliance=\"$appliance\", position=\"B7S2\"}"
      }
     ]
    },
    {
     "title": "Vendor ID",
     "type": "stat",
     "description": "Product ID the physical drive. Manufacturer serial number",
     "gridPos": { "h": 2, "w": 2, "x": 14, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "mqa_raid_physical_drive_info{appliance=\"$appliance\", position=\"B7S2\"}"
      }
     ]
    },
    {
     "title": "Product ID",
     "type": "stat",
     "description": "Product ID the physical drive. Manufacturer serial number",
     "gridPos": { "h": 2, "w": 2, "x": 16, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "mqa_raid_physical_drive_info{appliance=\"$appliance\", position=\"B7S2\"}"
      }
     ]
    },
    {
     "title": "Size",
     "type": "stat",
     "description": "Size of the physical drive in bytes",
     "gridPos": { "h": 2, "w": 2, "x": 18, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "mqa_raid_physical_drive_coerced_size_bytes_total{appliance=\"$appliance\", position=\"B7S2\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Storage - Appliance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "panels": [
    {
     "title": "Encrypted",
     "type": "gauge",
     "description": "Percentage of encrypted storage currently in use",
     "gridPos": { "h": 5, "w": 2, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "((mqa_file_system_encrypted_bytes_total{appliance=\"$appliance\"} - mqa_file_system_encrypted_bytes_free{appliance=\"$appliance\"}) / mqa_file_system_encrypted_bytes_total{appliance=\"$appliance\"}) * 100"
      }
     ]
    },
    {
     "title": "Total Encrypted",
     "type": "stat",
     "description": "Total encrypted storage available",
     "gridPos": { "h": 5, "w": 5, "x": 2, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "mqa_file_system_encrypted_bytes_total{appliance=\"$appliance\"}"
      }
     ]
    },
    {
     "title": "Free Encrypted",
     "type": "stat",
     "description": "Free encrypted storage available",
     "gridPos": { "h": 5, "w": 5, "x": 7, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "mqa_file_system_encrypted_bytes_free{appliance=\"$appliance\"}"
      }
     ]
    },
    {
     "title": "Temporary",
     "type": "gauge",
     "description": "Percentage of temporary storage currently in use",
     "gridPos": { "h": 5, "w": 2, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "((mqa_file_system_temporary_bytes_total{appliance=\"$appliance\"} - mqa_file_system_temporary_bytes_free{appliance=\"$appliance\"}) / mqa_file_system_temporary_bytes_total{appliance=\"$appliance\"}) * 100"
      }
     ]
    },
    {
     "title": "Total Temporary",
     "type": "stat",
     "description": "Total temporary storage available",
     "gridPos": { "h": 5, "w": 5, "x": 2, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "mqa_file_system_temporary_bytes_total{appliance=\"$appliance\"}"
      }
     ]
    },
    {
     "title": "Freel Temporary",
     "type": "stat",
     "description": "Free temporary storage available",
     "gridPos": { "h": 5, "w": 5, "x": 7, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "mqa_file_system_temporary_bytes_free{appliance=\"$appliance\"}"
      }
     ]
    },
    {
     "title": "Internal",
     "type": "gauge",
     "description": "Percentage of internal storage currently in use",
     "gridPos": { "h": 5, "w": 2, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "((mqa_file_system_internal_bytes_total{appliance=\"$appliance\"} - mqa_file_system_internal_bytes_free{appliance=\"$appliance\"}) / mqa_file_system_internal_bytes_total{appliance=\"$appliance\"}) * 100"
      }
     ]
    },
    {
     "title": "Total Internal",
     "type": "stat",
     "description": "Total internal storage available",
     "gridPos": { "h": 5, "w": 5, "x": 2, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "mqa_file_system_internal_bytes_total{appliance=\"$appliance\"}"
      }
     ]
    },
    {
     "title": "Free Internal",
     "type": "stat",
     "description": "Free internal storage available",
     "gridPos": { "h": 5, "w": 5, "x": 7, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "mqa_file_system_internal_bytes_free{appliance=\"$appliance\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Storage - MQ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "panels": [
    {
     "title": "MQ Data",
     "type": "gauge",
     "description": "Percentage of storage for MQ Data currently in use",
     "gridPos": { "h": 5, "w": 2, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "(mqa_mq_resources_storage_bytes_used{appliance=\"$appliance\"} / mqa_mq_resources_storage_bytes_total{appliance=\"$appliance\"}) * 100"
      }
     ]
    },
    {
     "title": "Total MQ Data",
     "type": "stat",
     "description": "Total storage for MQ Data currently allocated",
     "gridPos": { "h": 5, "w": 5, "x": 2, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "mqa_mq_resources_storage_bytes_total{appliance=\"$appliance\"}"
      }
     ]
    },
    {
     "title": "Used MQ Data",
     "type": "stat",
     "description": "Total storage for MQ Data currently in use",
     "gridPos": { "h": 5, "w": 5, "x": 7, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "mqa_mq_resources_storage_bytes_used{appliance=\"$appliance\"}"
      }
     ]
    },
    {
     "title": "Free MQ Data",
     "type": "stat",
     "description": "Amount of storage for MQ Data currently free",
     "gridPos": { "h": 5, "w": 5, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "mqa_mq_resources_storage_bytes_total{appliance=\"$appliance\"} - mqa_mq_resources_storage_bytes_used{appliance=\"$appliance\"}"
      }
     ]
    },
    {
     "title": "MQ Errors",
     "type": "gauge",
     "description": "Percentage of storage for MQ Errors currently in use",
     "gridPos": { "h": 5, "w": 2, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "(mqa_mq_resources_errors_storage_bytes_used{appliance=\"$appliance\"} / mqa_mq_resources_errors_storage_bytes_total{appliance=\"$appliance\"}) * 100"
      }
     ]
    },
    {
     "title": "Total MQ Errors",
     "type": "stat",
     "description": "Total storage for MQ Errors currently allocated",
     "gridPos": { "h": 5, "w": 5, "x": 2, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "mqa_mq_resources_errors_storage_bytes_total{appliance=\"$appliance\"}"
      }
     ]
    },
    {
     "title": "Used MQ Errors",
     "type": "stat",
     "description": "Total storage for MQ Errors currently allocated",
     "gridPos": { "h": 5, "w": 5, "x": 7, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "mqa_mq_resources_errors_storage_bytes_used{appliance=\"$appliance\"}"
      }
     ]
    },
    {
     "title": "Free MQ Errors",
     "type": "stat",
     "description": "Amount of storage for MQ Errors currently free",
     "gridPos": { "h": 5, "w": 5, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "mqa_mq_resources_errors_storage_bytes_total{appliance=\"$appliance\"} - mqa_mq_resources_errors_storage_bytes_used{appliance=\"$appliance\"}"
      }
     ]
    },
    {
     "title": "MQ Trace",
     "type": "gauge",
     "description": "Percentage of storage for MQ Trace currently in use",
     "gridPos": { "h": 5, "w": 2, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "(mqa_mq_resources_trace_storage_bytes_used{appliance=\"$appliance\"} / mqa_mq_resources_trace_storage_bytes_total{appliance=\"$appliance\"}) * 100"
      }
     ]
    },
    {
     "title": "Total MQ Trace",
     "type": "stat",
     "description": "Total storage for MQ Trace currently allocated",
     "gridPos": { "h": 5, "w": 5, "x": 2, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "mqa_mq_resources_trace_storage_bytes_total{appliance=\"$appliance\"}"
      }
     ]
    },
    {
     "title": "Used MQ Trace",
     "type": "stat",
     "description": "Amount of storage for MQ Trace currently in use",
     "gridPos": { "h": 5, "w": 5, "x": 7, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "mqa_mq_resources_trace_storage_bytes_used{appliance=\"$appliance\"}"
      }
     ]
    },
    {
     "title": "Free MQ trace",
     "type": "stat",
     "description": "Amount of storage for MQ Trace currently free",
     "gridPos": { "h": 5, "w": 5, "x": 12, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "mqa_mq_resources_trace_storage_bytes_total{appliance=\"$appliance\"} - mqa_mq_resources_trace_storage_bytes_used{appliance=\"$appliance\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Users",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Active Users",
     "type": "stat",
     "description": "Total number of users connected to the appliance, not counting any MQ users.",
     "gridPos": { "h": 6, "w": 3, "x": 0, "y": 20 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(mqa_active_users_total{appliance=\"$appliance\"})"
      }
     ]
    },
    {
     "title": "Active Users per Connection Types",
     "type": "graph",
     "description": "Active users based on their connection type, including SSH, Web UI, REST API, etc...",
     "gridPos": { "h": 6, "w": 21, "x": 3, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "mqa_active_users_total{appliance=\"$appliance\"}",
       "legendFormat": "{{connection}}"
      }
     ]
    }
   ]
  }
 ]
}