{
 "title": "MQ Appliance - Queue Managers",
 "description": "Metrics about the MQ Appliance queue managers",
 "tags": [ "MQA_Queue_Managers" ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "appliance", "label": "Appliance", "query": { "query": "mqa_info" } },
   {
    "name": "qm",
    "label": "QM",
    "query": {
     "query": "mqa_queue_manager_cpu_usage{appliance=\"$appliance\"}"
    }
   }
  ]
 },
 "panels": [
  { "title": "Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "stat",
   "description": "Status of the queue manager",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "mqa_queue_manager_info{appliance=\"$appliance\", qm=\"$qm\"}"
    }
   ]
  },
  {
   "title": "HA Role",
   "type": "stat",
   "description": "HA role of the queue manager",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "mqa_queue_manager_info{appliance=\"$appliance\", qm=\"$qm\"}"
    }
   ]
  },
  {
   "title": "HA Status",
   "type": "stat",
   "description": "HA status of the queue manager",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "mqa_queue_manager_info{appliance=\"$appliance\", qm=\"$qm\"}"
    }
   ]
  },
  {
   "title": "Appliance HA Status",
   "type": "stat",
   "description": "HA status of the appliance if the appliance is part of an HA group",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mqa_mq_resources_ha_status{appliance=\"$appliance\"}"
    }
   ]
  },
  { "title": "Local Date and Time", "type": "grafana-clock-panel", "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 } },
  {
   "title": "Appliance Date/Time",
   "type": "stat",
   "description": "The current local date and time on the appliance.",
   "gridPos": { "h": 2, "w": 4, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "time:ddd MMM DD HH:mm:ss YYYY" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "mqa_current_datetime_seconds_total{appliance=\"$appliance\"} * 1000"
    }
   ]
  },
  {
   "title": "Appliance Timezone",
   "type": "stat",
   "description": "The name of the time zone currently in effect.",
   "gridPos": { "h": 2, "w": 3, "x": 19, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "mqa_info{appliance=\"$appliance\"}"
    }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "description": "The version of this firmware image.",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "mqa_info{appliance=\"$appliance\"}"
    }
   ]
  },
  {
   "title": "DR Role",
   "type": "stat",
   "description": "DR role of the queue manager",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "mqa_queue_manager_info{appliance=\"$appliance\", qm=\"$qm\"}"
    }
   ]
  },
  {
   "title": "DR Status",
   "type": "stat",
   "description": "DR status of the queue manager",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "mqa_queue_manager_info{appliance=\"$appliance\", qm=\"$qm\"}"
    }
   ]
  },
  {
   "title": "Appliance HA Partner",
   "type": "stat",
   "description": "Appliance name of the HA partner and its associated status",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "mqa_mq_resources_info{appliance=\"$appliance\"}"
    }
   ]
  },
  {
   "title": "Exporter Date/Time",
   "type": "stat",
   "description": "The current local date and time on the server running the Prometheus exporter.",
   "gridPos": { "h": 2, "w": 4, "x": 15, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "time:ddd YYYY-MM-DD HH:mm:ss" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "mqa_exporter_current_datetime_seconds_total{appliance=\"$appliance\"} * 1000"
    }
   ]
  },
  {
   "title": "Exporter Timezone",
   "type": "stat",
   "description": "The name of the time zone currently in effect on the server running the Prometheus exporter.",
   "gridPos": { "h": 2, "w": 3, "x": 19, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "mqa_exporter_info{appliance=\"$appliance\"}"
    }
   ]
  },
  {
   "title": "Exporter Version",
   "type": "stat",
   "description": "The exporter version number of the Prometheus exporter.",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "mqa_exporter_info{appliance=\"$appliance\"}"
    }
   ]
  },
  { "title": "Queues", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Queue List and Depth",
   "type": "table",
   "description": "List of all LOCAL queues and their associated queue depth",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "mqa_qm_queue_current_depth{appliance=\"$appliance\", qm=\"$qm\"}",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Total Queues",
   "type": "stat",
   "description": "Total number of LOCAL queues",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(mqa_qm_queue_current_depth{appliance=\"$appliance\", qm=\"$qm\"})"
    }
   ]
  },
  {
   "title": "Queues with Depth",
   "type": "stat",
   "description": "Total number of LOCAL queues with a non-zero depth",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(mqa_qm_queue_current_depth{appliance=\"$appliance\", qm=\"$qm\"} > 0)"
    }
   ]
  },
  {
   "title": "Total SYSTEM Queues",
   "type": "stat",
   "description": "Total number of SYSTEM LOCAL queues",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(mqa_qm_queue_current_depth{appliance=\"$appliance\", qm=\"$qm\", queue=~\"SYSTEM.*\"})"
    }
   ]
  },
  {
   "title": "SYSTEM Queues with Depth",
   "type": "stat",
   "description": "Total number of SYSTEM LOCAL queues wit a non-zero depth",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(mqa_qm_queue_current_depth{appliance=\"$appliance\", qm=\"$qm\", queue=~\"SYSTEM.*\"} > 0)"
    }
   ]
  },
  {
   "title": "Non-Zero Queue Depth (highest to lowest)",
   "type": "stat",
   "description": "Queues with non-zero queue depth (highest to lowest)",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(mqa_qm_queue_current_depth{appliance=\"$appliance\", qm=\"$qm\"} > 0)",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": " CPU",
   "type": "gauge",
   "description": "Current CPU usage for the queue manager",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "mqa_queue_manager_cpu_usage{appliance=\"$appliance\", qm=\"$qm\"}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "description": "CPU usage for both the appliance and the queue manager",
   "gridPos": { "h": 5, "w": 10, "x": 2, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "mqa_queue_manager_cpu_usage{appliance=\"$appliance\", qm=\"$qm\"}",
     "legendFormat": "{{qm}}"
    },
    {
     "expr": "mqa_system_cpu_usage{appliance=\"$appliance\"}",
     "legendFormat": "Appliance"
    }
   ]
  },
  {
   "title": "CPU Usage Rate",
   "type": "graph",
   "description": "Rate of increase and decrease of CPU usage",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "deriv(mqa_queue_manager_cpu_usage{appliance=\"$appliance\", qm=\"$qm\"}[5m])",
     "legendFormat": "{{qm}}"
    },
    {
     "expr": "deriv(mqa_system_cpu_usage{appliance=\"$appliance\"}[5m])",
     "legendFormat": "Appliance"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "gauge",
   "description": "Current memory usage for the queue manager",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "((1 / mqa_system_memory_memory_bytes_total{appliance=\"$appliance\"}) * (scalar(mqa_queue_manager_memory_bytes_used{appliance=\"$appliance\", qm=\"$qm\"}))) * 100",
     "legendFormat": "Queue Manager"
    }
   ]
  },
  {
   "title": "Available Memory",
   "type": "stat",
   "description": "Total amount of memory still available",
   "gridPos": { "h": 2, "w": 3, "x": 2, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "mqa_system_memory_memory_bytes_free{appliance=\"$appliance\"}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "description": "Amount of memory used over time for both the appliance and the queue manager",
   "gridPos": { "h": 5, "w": 10, "x": 5, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "mqa_queue_manager_memory_bytes_used{appliance=\"$appliance\", qm=\"$qm\"}",
     "legendFormat": "{{qm}}"
    },
    {
     "expr": "mqa_system_memory_memory_bytes_used{appliance=\"$appliance\"}",
     "legendFormat": "Appliance"
    }
   ]
  },
  {
   "title": "Memory Usage Rate",
   "type": "graph",
   "description": "Rate of increase and decrease of memory used",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "deriv(mqa_queue_manager_memory_bytes_used{appliance=\"$appliance\", qm=\"$qm\"}[5m])",
     "legendFormat": "{{qm}}"
    },
    {
     "expr": "deriv(mqa_system_memory_memory_bytes_used{appliance=\"$appliance\"}[5m])",
     "legendFormat": "Appliance"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "stat",
   "description": "Amount of memory currently used by the queue manager",
   "gridPos": { "h": 3, "w": 3, "x": 2, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "mqa_queue_manager_memory_bytes_used{appliance=\"$appliance\", qm=\"$qm\"}"
    }
   ]
  },
  {
   "title": "File System",
   "type": "gauge",
   "description": "Current file system usage for the queue manager",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(mqa_queue_manager_fs_bytes_used{appliance=\"$appliance\", qm=\"$qm\"} / mqa_queue_manager_fs_bytes_allocated{appliance=\"$appliance\", qm=\"$qm\"}) * 100"
    }
   ]
  },
  {
   "title": "File System Allocated",
   "type": "stat",
   "description": "Total amount allocated for the queue manager file system",
   "gridPos": { "h": 2, "w": 3, "x": 2, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "mqa_queue_manager_fs_bytes_allocated{appliance=\"$appliance\", qm=\"$qm\"}"
    }
   ]
  },
  {
   "title": "File System Usage",
   "type": "graph",
   "description": "File system usage over time",
   "gridPos": { "h": 5, "w": 10, "x": 5, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "mqa_queue_manager_fs_bytes_used{appliance=\"$appliance\", qm=\"$qm\"}",
     "legendFormat": "{{qm}}"
    },
    {
     "expr": "mqa_mq_resources_storage_bytes_used{appliance=\"$appliance\"}",
     "legendFormat": "Appliance"
    }
   ]
  },
  {
   "title": "File System Usage Rate",
   "type": "graph",
   "description": "Rate of increase and decrease of file system used",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "deriv(mqa_queue_manager_fs_bytes_used{appliance=\"$appliance\", qm=\"$qm\"}[5m])",
     "legendFormat": "{{qm}}"
    },
    {
     "expr": "deriv(mqa_mq_resources_storage_bytes_used{appliance=\"$appliance\"}[5m])",
     "legendFormat": "Appliance"
    }
   ]
  },
  {
   "title": "File System Used",
   "type": "stat",
   "description": "Amount of file system currently used by the queue manager",
   "gridPos": { "h": 3, "w": 3, "x": 2, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "mqa_queue_manager_fs_bytes_used{appliance=\"$appliance\", qm=\"$qm\"}"
    }
   ]
  }
 ]
}