{
 "title": "MQ Appliance - Queues",
 "description": "Metrics about the MQ Appliance queues",
 "tags": [ "MQA_Queues" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "appliance", "label": "Appliance", "query": { "query": "mqa_info" } },
   {
    "name": "qm",
    "label": "QM",
    "query": {
     "query": "mqa_queue_manager_cpu_usage{appliance=\"$appliance\"}"
    }
   },
   {
    "name": "queue",
    "label": "Queue",
    "query": {
     "query": "mqa_qm_queue_current_depth{appliance=\"$appliance\", qm=\"$qm\"}"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Appliance Date/Time",
   "type": "stat",
   "description": "The current local date and time on the appliance.",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "time:ddd MMM DD HH:mm:ss YYYY" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "mqa_current_datetime_seconds_total{appliance=\"$appliance\"} * 1000"
    }
   ]
  },
  {
   "title": "Appliance Timezone",
   "type": "stat",
   "description": "The name of the time zone currently in effect.",
   "gridPos": { "h": 2, "w": 3, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "mqa_info{appliance=\"$appliance\"}"
    }
   ]
  },
  {
   "title": "Exporter Date/Time",
   "type": "stat",
   "description": "The current local date and time on the server running the Prometheus exporter.",
   "gridPos": { "h": 2, "w": 4, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "time:ddd MMM DD HH:mm:ss YYYY" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(mqa_exporter_current_datetime_seconds_total{appliance=\"$appliance\"} * 1000)"
    }
   ]
  },
  {
   "title": "Exporter Timezone",
   "type": "stat",
   "description": "The name of the time zone currently in effect on the server running the Prometheus exporter.",
   "gridPos": { "h": 2, "w": 3, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(mqa_exporter_info{appliance=\"$appliance\"}) by (localTimezone)"
    }
   ]
  },
  {
   "title": "Exporter Version",
   "type": "stat",
   "description": "The exporter version number of the Prometheus exporter.",
   "gridPos": { "h": 2, "w": 2, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(mqa_exporter_info{appliance=\"$appliance\"}) by (version)"
    }
   ]
  },
  {
   "title": "Last PUT Date/Time",
   "type": "stat",
   "description": "The date/time on which the last message was put to the queue since the queue manager started",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "time:ddd YYYY-MM-DD HH:mm:ss" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mqa_qm_queue_last_put_datetime_seconds_total{appliance=\"$appliance\", qm=\"$qm\", queue=\"$queue\"} * 1000"
    }
   ]
  },
  { "title": "Local Date and Time", "type": "grafana-clock-panel", "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 } },
  {
   "title": "Depth",
   "type": "stat",
   "description": "Current queue depth for the queue",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mqa_qm_queue_current_depth{appliance=\"$appliance\", qm=\"$qm\", queue=\"$queue\"}"
    }
   ]
  },
  {
   "title": "Uncommitted",
   "type": "stat",
   "description": "Number of uncommitted messages on the queue",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mqa_qm_queue_uncommitted_messages{appliance=\"$appliance\", qm=\"$qm\", queue=\"$queue\"}"
    }
   ]
  },
  {
   "title": "IPPROCS",
   "type": "stat",
   "description": "The number of handles that are currently open for input for the queue (either input-shared or input-exclusive)",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mqa_qm_queue_input_procs{appliance=\"$appliance\", qm=\"$qm\", queue=\"$queue\"}"
    }
   ]
  },
  {
   "title": "OPPROCS",
   "type": "stat",
   "description": "The number of handles that are currently open for output for the queue",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mqa_qm_queue_output_procs{appliance=\"$appliance\", qm=\"$qm\", queue=\"$queue\"}"
    }
   ]
  },
  {
   "title": "Message Age",
   "type": "stat",
   "description": "Age, in seconds, of the oldest message on the queue",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mqa_qm_queue_message_age_seconds{appliance=\"$appliance\", qm=\"$qm\", queue=\"$queue\"}"
    }
   ]
  },
  {
   "title": "Q-Time",
   "type": "stat",
   "description": "Interval, in microseconds, between messages being put on the queue and then being destructively read",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mqa_qm_queue_time_small_sample_seconds{appliance=\"$appliance\", qm=\"$qm\", queue=\"$queue\"}"
    },
    {
     "expr": "mqa_qm_queue_time_large_sample_seconds{appliance=\"$appliance\", qm=\"$qm\", queue=\"$queue\"}"
    }
   ]
  },
  {
   "title": "Current FS",
   "type": "stat",
   "description": "The current size of the queue file in bytes, rounded up to the nearest megabyte",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mqa_qm_queue_current_file_size_bytes{appliance=\"$appliance\", qm=\"$qm\", queue=\"$queue\"}"
    }
   ]
  },
  {
   "title": "Maximum FS",
   "type": "stat",
   "description": "The current maximum size the queue file can grow to, rounded up to the nearest megabyte, given the current block size in use on a queue",
   "gridPos": { "h": 2, "w": 2, "x": 14, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mqa_qm_queue_current_max_file_size_bytes{appliance=\"$appliance\", qm=\"$qm\", queue=\"$queue\"}"
    }
   ]
  },
  {
   "title": "Last GET Date/Time",
   "type": "stat",
   "description": "The date/time at which the last message was retrieved from the queue since the queue manager started",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "time:ddd YYYY-MM-DD HH:mm:ss" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mqa_qm_queue_last_get_datetime_seconds_total{appliance=\"$appliance\", qm=\"$qm\", queue=\"$queue\"} * 1000"
    }
   ]
  },
  {
   "title": "Queue Depth",
   "type": "graph",
   "description": "Queue depth over time",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mqa_qm_queue_current_depth{appliance=\"$appliance\", qm=\"$qm\", queue=\"$queue\"}",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "IPPROCS",
   "type": "graph",
   "description": "IPPROCS over time",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mqa_qm_queue_input_procs{appliance=\"$appliance\", qm=\"$qm\", queue=\"$queue\"}",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Age of Oldest Message",
   "type": "graph",
   "description": "Age of oldest message in seconds over time",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "mqa_qm_queue_message_age_seconds{appliance=\"$appliance\", qm=\"$qm\", queue=\"$queue\"}",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "OPPROCS",
   "type": "graph",
   "description": "OPPROCS over time",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mqa_qm_queue_output_procs{appliance=\"$appliance\", qm=\"$qm\", queue=\"$queue\"}",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Q-Time Last Few Messages",
   "type": "graph",
   "description": "Interval, in seconds, between messages being put on the queue and then being destructively read. A value based on the last few messages processed",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "mqa_qm_queue_time_small_sample_seconds{appliance=\"$appliance\", qm=\"$qm\", queue=\"$queue\"}",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Q-Time Larger Sample of  Messages",
   "type": "graph",
   "description": "Interval, in seconds, between messages being put on the queue and then being destructively read. A value based on a larger sample of the recently processed messages",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "mqa_qm_queue_time_large_sample_seconds{appliance=\"$appliance\", qm=\"$qm\", queue=\"$queue\"}",
     "legendFormat": "{{queue}}"
    }
   ]
  }
 ]
}