{
 "title": "MQ Appliance - Channels",
 "description": "Metrics about the MQ Appliance channels",
 "tags": [ "MQA_Channels" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "appliance", "label": "Appliance", "query": { "query": "mqa_info" } },
   {
    "name": "qm",
    "label": "QM",
    "query": {
     "query": "mqa_queue_manager_cpu_usage{appliance=\"$appliance\"}"
    }
   },
   {
    "name": "type",
    "label": "Type",
    "query": "CLUSRCVR,CLUSSDR,RCVR,RQSTR,SDR,SVR,SVRCONN"
   },
   {
    "name": "name",
    "label": "Name",
    "query": {
     "query": "mqa_qm_channel_info{appliance=\"$appliance\", qm=\"$qm\", chlType=\"$type\"}"
    }
   },
   {
    "name": "jobname",
    "label": "Job Name",
    "query": {
     "query": "mqa_qm_channel_info{appliance=\"$appliance\", qm=\"$qm\", chlType=\"$type\", channel=\"$name\"}"
    }
   }
  ]
 },
 "panels": [
  { "title": "All Instances", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Channel Instances",
   "type": "stat",
   "description": "The total number of current channel instances for that specific channel",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(mqa_qm_channel_info{appliance=\"$appliance\", qm=\"$qm\", chlType=\"$type\", channel=\"$name\"})"
    }
   ]
  },
  {
   "title": "Total Disctinct IPs",
   "type": "stat",
   "description": "The total number of distinct IPs using the current channel instances",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(mqa_qm_channel_info{appliance=\"$appliance\", qm=\"$qm\", chlType=\"$type\", channel=\"$name\"}) by (conName))"
    }
   ]
  },
  {
   "title": "Total Disctinct Queue Managers",
   "type": "stat",
   "description": "The total number of distinct queue managers using the current channel instances",
   "gridPos": { "h": 2, "w": 4, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(mqa_qm_channel_info{appliance=\"$appliance\", qm=\"$qm\", chlType=\"$type\", channel=\"$name\"}) by (remoteQMgr))"
    }
   ]
  },
  { "title": "Local Date and Time", "type": "grafana-clock-panel", "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 } },
  {
   "title": "Exporter Date/Time",
   "type": "stat",
   "description": "The current local date and time on the server running the Prometheus exporter.",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "time:ddd MMM DD HH:mm:ss YYYY" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(mqa_exporter_current_datetime_seconds_total{appliance=\"$appliance\"} * 1000)"
    }
   ]
  },
  {
   "title": "Appliance Date/Time",
   "type": "stat",
   "description": "The current local date and time on the appliance.",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "time:ddd MMM DD HH:mm:ss YYYY" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "mqa_current_datetime_seconds_total{appliance=\"$appliance\"} * 1000"
    }
   ]
  },
  {
   "title": "Total Messages",
   "type": "stat",
   "description": "The total number of messages for all current channel instances",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(mqa_qm_channel_messages_total{appliance=\"$appliance\", qm=\"$qm\", chlType=\"$type\", channel=\"$name\"})"
    }
   ]
  },
  {
   "title": "Total Disctinct Versions",
   "type": "stat",
   "description": "The total number of distinct versions using the current channel instances",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(mqa_qm_channel_info{appliance=\"$appliance\", qm=\"$qm\", chlType=\"$type\", channel=\"$name\"}) by (remoteVersion))"
    }
   ]
  },
  {
   "title": "Total Disctinct Products",
   "type": "stat",
   "description": "The total number of distinct products using the current channel instances",
   "gridPos": { "h": 2, "w": 4, "x": 6, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(mqa_qm_channel_info{appliance=\"$appliance\", qm=\"$qm\", chlType=\"$type\", channel=\"$name\"}) by (remoteProduct))"
    }
   ]
  },
  {
   "title": "Exporter Timezone",
   "type": "stat",
   "description": "The name of the time zone currently in effect on the server running the Prometheus exporter.",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(mqa_exporter_info{appliance=\"$appliance\"}) by (localTimezone)"
    }
   ]
  },
  {
   "title": "Appliance Timezone",
   "type": "stat",
   "description": "The name of the time zone currently in effect.",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "mqa_info{appliance=\"$appliance\"}"
    }
   ]
  },
  {
   "title": "Channel Instances List",
   "type": "table",
   "description": "The list of all current channel instances",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "mqa_qm_channel_info{appliance=\"$appliance\", qm=\"$qm\", chlType=\"$type\", channel=\"$name\"}"
    }
   ]
  },
  {
   "title": "Message Rate per Seconds",
   "type": "graph",
   "description": "Rate of the messages per seconds over a 5 minutes period",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(mqa_qm_channel_messages_total{appliance=\"$appliance\", qm=\"$qm\", chlType=\"$type\", channel=\"$name\"}[2m]))",
     "legendFormat": "All instances"
    }
   ]
  },
  {
   "title": "Total Channel Instances by IPs",
   "type": "stat",
   "description": "The total number of current channel instances by IPs for that specific channel",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(mqa_qm_channel_info{appliance=\"$appliance\", qm=\"$qm\", chlType=\"$type\", channel=\"$name\"})  by (conName)",
     "legendFormat": "{{conName}}"
    }
   ]
  },
  {
   "title": "Total Channel Instances by Remote Queue Managers",
   "type": "stat",
   "description": "The total number of current channel instances by remote queue managers for that specific channel",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(mqa_qm_channel_info{appliance=\"$appliance\", qm=\"$qm\", chlType=\"$type\", channel=\"$name\"})  by (remoteQMgr)",
     "legendFormat": "{{remoteQMgr}}"
    }
   ]
  },
  {
   "title": "Total Channel Instances by Remote Versions",
   "type": "stat",
   "description": "The total number of current channel instances by remote versions for that specific channel",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(mqa_qm_channel_info{appliance=\"$appliance\", qm=\"$qm\", chlType=\"$type\", channel=\"$name\"})  by (remoteVersion)",
     "legendFormat": "{{remoteVersion}}"
    }
   ]
  },
  {
   "title": "Total Channel Instances by Remote Products",
   "type": "stat",
   "description": "The total number of current channel instances by remote products for that specific channel",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(mqa_qm_channel_info{appliance=\"$appliance\", qm=\"$qm\", chlType=\"$type\", channel=\"$name\"})  by (remoteProduct)",
     "legendFormat": "{{remoteProduct}}"
    }
   ]
  },
  {
   "title": "Specific Instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true
  },
  {
   "title": "Job Name",
   "type": "stat",
   "description": "The job name under which the channel is  running",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mqa_qm_channel_info{appliance=\"$appliance\", qm=\"$qm\", chlType=\"$type\", channel=\"$name\", jobName=\"$jobname\"}"
    }
   ]
  },
  {
   "title": "Start Date and Time",
   "type": "stat",
   "description": "The date and time the channel instance started",
   "gridPos": { "h": 2, "w": 4, "x": 3, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "time:ddd MMM DD HH:mm:ss YYYY" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mqa_qm_channel_start_datetime_seconds_total{appliance=\"$appliance\", qm=\"$qm\", chlType=\"$type\", channel=\"$name\", jobName=\"$jobname\"} * 1000"
    }
   ]
  },
  {
   "title": "Last Message Date and Time",
   "type": "stat",
   "description": "The date and time of the last message going over the channel instance",
   "gridPos": { "h": 2, "w": 4, "x": 7, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "time:ddd MMM DD HH:mm:ss YYYY" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mqa_qm_channel_last_message_datetime_seconds_total{appliance=\"$appliance\", qm=\"$qm\", chlType=\"$type\", channel=\"$name\", jobName=\"$jobname\"} * 1000"
    }
   ]
  },
  {
   "title": "Total Messages",
   "type": "stat",
   "description": "The total number of messages for all current channel instances",
   "gridPos": { "h": 2, "w": 3, "x": 11, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(mqa_qm_channel_messages_total{appliance=\"$appliance\", qm=\"$qm\", chlType=\"$type\", channel=\"$name\", jobName=\"$jobname\"})"
    }
   ]
  },
  {
   "title": "Message Rate per Seconds",
   "type": "graph",
   "description": "Rate of the messages per seconds over a 5 minutes period",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(mqa_qm_channel_messages_total{appliance=\"$appliance\", qm=\"$qm\", chlType=\"$type\", channel=\"$name\", jobName=\"$jobname\"}[2m])",
     "legendFormat": "{{jobName}}"
    }
   ]
  }
 ]
}